export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const GET_USERS = 'GET_USERS';
export const LOADING_USERS = 'LOADING_USERS';
export const ERROR_USERS = 'ERROR_USERS';

export const GET_MESSAGES = 'GET_MESSAGES';

export const ADD_MESSAGE = 'ADD_MESSAGE';
